# Generated by Django 3.2.13 on 2022-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
