# Generated by Django 3.2.13 on 2022-05-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_tenant_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
